spring.application.name=khohang

# ===============================
# DATABASE H2
# ===============================
spring.datasource.url=jdbc:h2:file:./data/khohangdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# GOOGLE LOGIN
# ===============================
spring.security.oauth2.client.registration.google.client-id=336223277538-gvgkcrkhlfidjc8md980nvqa16ife43u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email